name: lint

on:
  push:
    branches: [ main ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - run: sudo gem install chef-utils -v 16.6.14
      - run: sudo gem install mdl
      - run: mdl /docs -r ~MD013
