name: mdlint

on:
  push:
    branches: [ main ]

jobs:
  mdlint:
    runs-on: ubuntu-latest
    steps:
      - run: sudo gem install chef-utils -v 16.6.14
      - run: sudo gem install mdl
      - run: mdl docs/ -r ~MD013
